.PHONY: build up down

build:
	sudo docker compose build

up:
	sudo docker compose up

down:
	sudo docker compose down

install:
	yarn install

serve:
	yarn serve

clean:
	sudo docker system prune -a --volumes