networks:
  speakup.net:
    driver: bridge

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file: ./gateway/.env
    ports:
      - "${GATEWAY_PORT}:80"
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - speakup.net
    depends_on:
      - messages.db
      - users.db
      - rooms.db
      - credentials.db

  api.message:
    build:
      context: ./message
      dockerfile: Dockerfile
    env_file: ./message/.env
    ports:
      - "${MESSAGE_PORT}:80"
    volumes:
      - ./message/sql:/var/php/sql
    working_dir: /var/php
    networks:
      - speakup.net
    depends_on:
      - messages.db 

  api.user:
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file: ./user/.env
    ports:
      - "${USER_PORT}:80"
    volumes:
      - ./user:/var/php
    working_dir: /var/php
    networks:
      - speakup.net
    depends_on:
      - users.db

  api.communication:
    build:
      context: ./communication
      dockerfile: Dockerfile
    env_file: ./communication/.env
    ports:
      - "${COMMUNICATION_PORT}:80"
    volumes:
      - ./communication:/var/php
    working_dir: /var/php
    networks:
      - speakup.net

  api.room:
    build:
      context: ./room
      dockerfile: Dockerfile
    env_file: ./room/.env
    ports:
      - "${ROOM_PORT}:80"
    volumes:
      - ./room:/var/php
    working_dir: /var/php
    networks:
      - speakup.net
    depends_on:
      - rooms.db

  api.auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file: ./auth/.env
    ports:
      - "${AUTH_PORT}:80"
    volumes:
      - ./auth:/var/php
    working_dir: /var/php
    networks:
      - speakup.net
    depends_on:
      - users.db

  messages.db:
    image: 'scylladb/scylla:latest'
    env_file: ./message/.env
    ports:
      - "${MESSAGES_DB_PORT:-9042}:9042"
    networks:
      - speakup.net
    volumes:
      - ./message/sql:/docker-entrypoint-initdb.d

  users.db:
    image: 'mariadb:latest'
    env_file: ./user/.env
    ports:
      - "${USERS_DB_PORT:-3306}:3306"
    networks:
      - speakup.net
    volumes:
      - ./user/sql:/docker-entrypoint-initdb.d

  credentials.db:
    image: 'mariadb:latest'
    env_file: ./auth/.env
    ports:
      - "${CREDENTIALS_DB_PORT:-3307}:3306"
    networks:
      - speakup.net
    volumes:
      - ./auth/sql:/docker-entrypoint-initdb.d

  rooms.db:
    image: 'mariadb:latest'
    env_file: ./room/.env
    ports:
      - "${ROOMS_DB_PORT:-3308}:3306"
    networks:
      - speakup.net
    volumes:
      - ./room/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    networks:
      - speakup.net
